language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
env:
  - PYTHON=""
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("FTPClient"))
      Pkg.add("Coverage"); using Coverage
      Codecov.submit(process_folder())'
